const centerRows = [];
const pendingRows = [];
const KURRO_CACHE_KEY='kurro-remote-cache-v2';

const $ = id => document.getElementById(id);
function loadSavedData(){try{const cached=JSON.parse(localStorage.getItem(KURRO_CACHE_KEY)||'null');if(!cached)return false;centerRows.splice(0,centerRows.length,...(cached.center||[]));pendingRows.splice(0,pendingRows.length,...(cached.pending||[]));return centerRows.length>0||pendingRows.length>0}catch(e){return false}}
function saveData(){try{localStorage.setItem(KURRO_CACHE_KEY,JSON.stringify({center:centerRows,pending:pendingRows,updated:new Date().toISOString()}))}catch(e){}}
function metric(label,value,note,alert=false){return `<div class="metric ${alert?'alert':''}"><div class="metric-label">${label}</div><div class="metric-value">${value}</div><div class="metric-note">${note}</div></div>`}
function statusTag(s){const label=s==='done'?'REALIZADO':s==='process'?'EN PROCESO':'PENDIENTE';return `<span class="status ${s==='done'?'done':s==='process'?'process':'open'}"><span class="status-dot"></span>${label}</span>`}
function addMonths(date, months){const d=new Date(date+'T12:00:00');const day=d.getDate();d.setMonth(d.getMonth()+months);if(d.getDate()!==day)d.setDate(0);return d}
function nextDate(date,frequency){const d=new Date(date+'T12:00:00');const f=(frequency||'').toLowerCase();if(f.includes('seman'))d.setDate(d.getDate()+7);else if(f.includes('bimes'))return addMonths(date,2);else if(f.includes('trimes'))return addMonths(date,3);else if(f.includes('semes'))return addMonths(date,6);else if(f.includes('mens'))return addMonths(date,1);else if(f.includes('5 años'))return addMonths(date,60);else if(f.includes('3 años'))return addMonths(date,36);else if(f.includes('año')||f.includes('anual'))return addMonths(date,12);else return null;return d}
function formatDate(d){return d?`${String(d.getDate()).padStart(2,'0')}/${String(d.getMonth()+1).padStart(2,'0')}/${d.getFullYear()}`:''}
function normalizeSheetDate(value){const s=String(value||'').trim();let m=s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);if(m)return`${m[1].padStart(2,'0')}/${m[2].padStart(2,'0')}/${m[3]}`;m=s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/);return m?`${m[3].padStart(2,'0')}/${m[2].padStart(2,'0')}/${m[1]}`:s}
function isOverdue(r){if(!r.next)return false;const p=r.next.split('/');const due=new Date(`${p[2]}-${p[1]}-${p[0]}T23:59:59`);return due<new Date()}
function dueTone(r){if(!r.next)return '';const p=r.next.split('/');const due=new Date(`${p[2]}-${p[1]}-${p[0]}T23:59:59`);const days=Math.ceil((due-new Date())/86400000);return days<0?'row-overdue':days<=30?'row-soon':'row-ok'}
function effectiveStatus(r){return isOverdue(r)&&r.status==='done'?'open':r.status}
function markCenterDone(index){const input=$(`done-date-${index}`);if(!input||!input.value){$('toast').textContent='Elige primero la fecha en la que se ha hecho';$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2800);return}const r=centerRows[index];if(isOverdue(r)){r.status='process';$('toast').textContent='Esta actividad está vencida y no puede marcarse como realizada. Déjala pendiente o en proceso.';$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),3600);renderCenter();return}r.last=formatDate(new Date(input.value+'T12:00:00'));const next=nextDate(input.value,r.frequency);r.next=formatDate(next);r.status='done';r.action='REALIZADO';renderCenter();$('toast').textContent=next?`Marcado como hecho. Próxima revisión: ${r.next}`:'Marcado como hecho. Esta actividad no tiene periodicidad calculable.';$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),3200)}
function updateCenterField(index,field,value){const r=centerRows[index];if(field==='status'&&value==='done'&&isOverdue(r)){r.status='process';$('toast').textContent='Una actividad vencida solo puede estar pendiente o en proceso';$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),3000);renderCenter();return}r[field]=value;saveData();}
function sortValue(r,key){if(key==='category')return r.category;if(key==='last')return r.last?new Date(r.last.split('/').reverse().join('-')):new Date(0);if(key==='next')return r.next?new Date(r.next.split('/').reverse().join('-')):new Date(8640000000000000);if(key==='frequency')return r.frequency||'zzzz';if(key==='status')return r.status;return r.activity}
function renderCenter(){const q=($('center-search').value||'').toLowerCase(), cat=$('center-category').value, state=$('center-status').value, sort=$('center-sort').value;const rows=centerRows.filter(r=>(cat==='all'||r.category===cat)&&(state==='all'||(state==='done'?effectiveStatus(r)==='done':state==='process'?effectiveStatus(r)==='process':effectiveStatus(r)==='open'))&&[r.activity,r.category,r.frequency,r.last,r.next,r.owner,r.action].join(' ').toLowerCase().includes(q)).sort((a,b)=>{const av=sortValue(a,sort),bv=sortValue(b,sort);return av>bv?1:av<bv?-1:0});$('center-table').innerHTML=rows.length?rows.map(r=>{const i=centerRows.indexOf(r),st=effectiveStatus(r),overdue=isOverdue(r);return `<tr class="${dueTone(r)}"><td>${r.activity}</td><td>${r.category}</td><td>${r.frequency||'<span class="muted">Sin periodicidad</span>'}</td><td class="date">${normalizeSheetDate(r.last)||'<span class="muted">Sin fecha</span>'}</td><td class="date">${normalizeSheetDate(r.next)||'<span class="muted">Sin fecha</span>'}${overdue?' <span class="overdue-label">VENCIDA</span>':''}</td><td>${r.owner||'<span class="muted">Sin asignar</span>'}</td><td>${statusTag(st)}</td><td>${r.action||'<span class="muted">Sin comentarios</span>'}</td><td><div class="row-actions"><input id="done-date-${i}" type="date" aria-label="Fecha de la actuación para ${r.activity}" ${overdue?'disabled':''}/><button class="done-btn" onclick="${overdue?`openCenterEditor(${i})`:`markCenterDone(${i})`}">${overdue?'Registrar seguimiento':'Registrar revisión'}</button><button class="edit-btn" onclick="openCenterEditor(${i})">Editar</button></div></td></tr>`}).join(''):`<tr><td colspan="9" class="empty">No hay resultados con estos filtros.</td></tr>`;$('center-count').textContent=`${rows.length} registros`;}
function renderPending(){const q=($('pending-search').value||'').toLowerCase(), person=window.person||'all', priority=$('pending-priority').value,state=$('pending-status').value;const rows=pendingRows.filter(r=>(person==='all'||r.person===person)&&(priority==='all'||r.priority===priority)&&(state==='all'||r.status===state)&&[r.person,r.text,r.priority].join(' ').toLowerCase().includes(q));$('pending-table').innerHTML=rows.length?rows.map(r=>`<tr><td>${r.status==='PENDIENTE'?'<span class="status open"><span class="status-dot"></span>PENDIENTE</span>':'<span class="status done">REALIZADO</span>'}</td><td>${r.text}</td><td><strong>${r.person}</strong></td><td><span class="priority">${r.priority}</span></td><td class="date">${r.date||'<span class="muted">Sin fecha</span>'}</td><td class="date">${r.updated}</td></tr>`).join(''):`<tr><td colspan="6" class="empty">No hay resultados con estos filtros.</td></tr>`;$('pending-heading').textContent=person==='all'?'Todos mis pendientes':`Pendientes con ${person}`;$('pending-count').textContent=`${rows.length} registros`;}
function init(){const cats=[...new Set(centerRows.map(r=>r.category))].sort();$('center-category').innerHTML='<option value="all">Todas las categorías</option>'+cats.map(c=>`<option>${c}</option>`).join('');$('center-metrics').innerHTML=metric('Actividades registradas',centerRows.length,'Registro maestro')+metric('Pendientes de centro',centerRows.filter(r=>r.status==='open').length,'Requieren seguimiento',true)+metric('En proceso',centerRows.filter(r=>r.status==='process').length,'Acciones abiertas')+metric('Próximas revisiones',centerRows.filter(r=>r.next).length,'Con fecha definida');$('pending-metrics').innerHTML=metric('Pendientes totales',pendingRows.length,'Miguel + Properval')+metric('Con Miguel',pendingRows.filter(r=>r.person==='Miguel').length,'Seguimiento activo')+metric('Con Properval',pendingRows.filter(r=>r.person==='Properval').length,'Seguimiento activo')+metric('Con fecha objetivo',pendingRows.filter(r=>r.date).length,'Para priorizar');$('people-tabs').innerHTML=['all','Miguel','Properval'].map(p=>`<button class="person-tab ${p==='all'?'active':''}" data-person="${p}">${p==='all'?'Todos':p}</button>`).join('');document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));$(`${b.dataset.view}-view`).classList.add('active-view');$('page-title').textContent=b.dataset.view==='center'?'Centro':'Mis pendientes'}));document.querySelectorAll('.person-tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.person-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');window.person=b.dataset.person;renderPending()}));['center-search','center-category','center-status','center-sort'].forEach(id=>$(id).addEventListener('input',renderCenter));['pending-search','pending-priority','pending-status'].forEach(id=>$(id).addEventListener('input',renderPending));document.querySelectorAll('[data-toast]').forEach(b=>b.addEventListener('click',()=>{ $('toast').textContent=b.dataset.toast;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2800)}));renderCenter();renderPending();}loadSavedData();window.person='all';init();
function updatePendingField(index,field,value){pendingRows[index][field]=value;saveData()}
function markPendingDone(index){pendingRows[index].status='REALIZADO';pendingRows[index].updated=formatDate(new Date());saveData();renderPending()}
setTimeout(()=>renderPending(),0);

// Opciones ampliables para que los nuevos responsables y contactos sigan disponibles.
const KURRO_LISTS_KEY='kurro-lists-v1';
function savedKurroLists(){try{return JSON.parse(localStorage.getItem(KURRO_LISTS_KEY)||'{}')}catch(e){return {}}}
let remoteKurroLists={};
function mergedKurroLists(){const local=savedKurroLists();const merged={};Object.keys({...local,...remoteKurroLists}).forEach(k=>{merged[k]=[...new Set([...(remoteKurroLists[k]||[]),...(local[k]||[])].map(v=>String(v||'').trim()).filter(Boolean))]});return merged}
function saveRemoteKurroLists(rows){const out={};(rows||[]).slice(1).forEach(row=>{const type=String(row[0]||'').trim().toLowerCase(),value=String(row[1]||'').trim(),active=String(row[2]||'TRUE').toUpperCase();if(type&&value&&active!=='FALSE') (out[type]||(out[type]=[])).push(value)});remoteKurroLists=out}
function saveKurroLists(lists){try{localStorage.setItem(KURRO_LISTS_KEY,JSON.stringify(lists))}catch(e){}}
function kurroOptions(kind){const lists=mergedKurroLists(),source=kind==='owner'?centerRows.map(r=>r.owner):pendingRows.map(r=>r.person);return [...new Set([...(lists[kind]||[]),...source].map(v=>String(v||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'))}
function fillKurroSelect(id,values,current=''){const select=$(id);if(!select)return;const value=current||select.value;select.innerHTML=(id==='edit-owner'?'<option value="">Sin asignar</option>':'')+values.map(v=>`<option value="${String(v).replaceAll('&','&amp;').replaceAll('"','&quot;')}">${String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')}</option>`).join('');if(value&&values.includes(value))select.value=value}
function refreshKurroPeopleOptions(){fillKurroSelect('edit-owner',kurroOptions('owner'));fillKurroSelect('pending-edit-person',kurroOptions('person'))}
function addKurroOption(kind,selectId,label){const name=prompt(label);if(!name)return;const clean=name.trim();if(!clean)return;const lists=savedKurroLists();lists[kind]=[...(lists[kind]||[]),clean];saveKurroLists(lists);refreshKurroPeopleOptions();$(selectId).value=clean;showSyncToast(`${clean} añadido a la lista`)}
function renderCenterWithoutDuplicateAction(){const originalCenterRows=[...centerRows];const q=($('center-search').value||'').toLowerCase(),cat=$('center-category').value,state=$('center-status').value,sort=$('center-sort').value;const rows=originalCenterRows.filter(r=>(cat==='all'||r.category===cat)&&(state==='all'||(state==='done'?effectiveStatus(r)==='done':state==='process'?effectiveStatus(r)==='process':effectiveStatus(r)==='open'))&&[r.activity,r.category,r.frequency,r.last,r.next,r.owner,r.action].join(' ').toLowerCase().includes(q)).sort((a,b)=>{const av=sortValue(a,sort),bv=sortValue(b,sort);return av>bv?1:av<bv?-1:0});$('center-table').innerHTML=rows.length?rows.map(r=>{const i=centerRows.indexOf(r),overdue=isOverdue(r);return `<tr class="${dueTone(r)}"><td>${r.activity}</td><td>${r.category}</td><td>${r.frequency||'<span class="muted">Sin periodicidad</span>'}</td><td class="date">${normalizeSheetDate(r.last)||'<span class="muted">Sin fecha</span>'}</td><td class="date">${normalizeSheetDate(r.next)||'<span class="muted">Sin fecha</span>'}${overdue?' <span class="overdue-label">VENCIDA</span>':''}</td><td>${r.owner||'<span class="muted">Sin asignar</span>'}</td><td>${statusTag(effectiveStatus(r))}</td><td>${r.action||'<span class="muted">Sin comentarios</span>'}</td><td><div class="row-actions"><button class="edit-btn" onclick="openCenterEditor(${i})">Editar</button></div></td></tr>`}).join(''):`<tr><td colspan="9" class="empty">No hay resultados con estos filtros.</td></tr>`;$('center-count').textContent=`${rows.length} registros`}
renderCenter=renderCenterWithoutDuplicateAction;
refreshKurroPeopleOptions();
document.querySelector('#add-owner')?.addEventListener('click',()=>addKurroOption('owner','edit-owner','Escribe el nuevo responsable'));
document.querySelector('#add-pending-person')?.addEventListener('click',()=>addKurroOption('person','pending-edit-person','Escribe la nueva persona o empresa'));
const originalOpenCenterEditor=openCenterEditor;openCenterEditor=function(index){refreshKurroPeopleOptions();originalOpenCenterEditor(index)};
const originalOpenNewCenterEditor=openNewCenterEditor;openNewCenterEditor=function(){refreshKurroPeopleOptions();originalOpenNewCenterEditor()};
const originalOpenPendingEditor=openPendingEditor;openPendingEditor=function(index=-1){refreshKurroPeopleOptions();originalOpenPendingEditor(index)};
const originalSavePendingEditor=savePendingEditor;savePendingEditor=async function(){const person=$('pending-edit-person')?.value;const previous=window.person;const sourcePerson=previous==='Properval'?'Properval':'Miguel';window.kurroPendingSource=sourcePerson;await originalSavePendingEditor();window.person=previous;};
renderPending=function(){const q=($('pending-search').value||'').toLowerCase(),person=window.person||'all',priority=$('pending-priority').value,state=$('pending-status').value;const rows=pendingRows.filter(r=>(person==='all'||r.person===person)&&(priority==='all'||r.priority===priority)&&(state==='all'||r.status===state)&&[r.person,r.text,r.priority,r.comments].join(' ').toLowerCase().includes(q));$('pending-table').innerHTML=rows.length?rows.map(r=>{const i=pendingRows.indexOf(r);return `<tr><td><select class="status-select" aria-label="Estado de ${r.text}" onchange="updatePendingField(${i},'status',this.value)"><option ${r.status==='PENDIENTE'?'selected':''}>PENDIENTE</option><option ${r.status==='REALIZADO'?'selected':''}>REALIZADO</option></select></td><td>${r.text}</td><td><strong>${r.person}</strong></td><td><select class="status-select" aria-label="Prioridad de ${r.text}" onchange="updatePendingField(${i},'priority',this.value)"><option ${r.priority==='NORMAL'?'selected':''}>NORMAL</option><option ${r.priority==='ALTA'?'selected':''}>ALTA</option></select></td><td class="date"><input class="pending-date" type="date" aria-label="Fecha objetivo de ${r.text}" value="${pendingDateForEditor(r.date)}" onchange="updatePendingField(${i},'date',pendingDateFromEditor(this.value))"></td><td class="date">${r.updated||'<span class="muted">Sin fecha</span>'}</td><td><textarea class="comment-input" rows="2" placeholder="Añadir comentario" oninput="this.style.height='auto';this.style.height=this.scrollHeight+'px'" onchange="updatePendingField(${i},'comments',this.value)">${r.comments||''}</textarea></td><td><div class="pending-person"><button class="done-btn" onclick="updatePendingField(${i},'status','REALIZADO')" ${r.status==='REALIZADO'?'disabled':''}>Hecho</button><button class="edit-btn" onclick="openPendingEditor(${i})">Editar</button></div></td></tr>`}).join(''):`<tr><td colspan="8" class="empty">No hay resultados con estos filtros.</td></tr>`;$('pending-heading').textContent=person==='all'?'Todos mis pendientes':`Pendientes con ${person}`;$('pending-count').textContent=`${rows.length} registros`};
renderCenter();renderPending();
// La próxima revisión se calcula por defecto, pero admite una fecha manual.
const legacyOpenCenterEditor= openCenterEditor, legacyOpenNewCenterEditor=openNewCenterEditor;
openCenterEditor=function(index){legacyOpenCenterEditor(index);if($('edit-next'))$('edit-next').dataset.manual='false'};
openNewCenterEditor=function(){legacyOpenNewCenterEditor();if($('edit-next'))$('edit-next').dataset.manual='false'};
const legacyNextPreview=updateEditorNextPreview;
$('edit-next')?.addEventListener('input',()=>{$('edit-next').dataset.manual='true'});
function saveCenterEditorFlexible(){const index=centerEditorIndex,isNew=index===-1,r=isNew?{}:centerRows[index];if(!r)return;const frequency=$('edit-frequency').value==='custom'?$('edit-frequency-custom').value.trim():$('edit-frequency').value;const last=$('edit-last').value?dateFromEditor($('edit-last').value):'';const manualNext=$('edit-next').dataset.manual==='true';const calculated=last&&frequency?nextDate($('edit-last').value,frequency):null;const next=manualNext?($('edit-next').value?dateFromEditor($('edit-next').value):''):(calculated?formatDate(calculated):'');const changes={activity:$('edit-activity').value.trim(),category:$('edit-category').value.trim()||'Otros',frequency,last,next,owner:$('edit-owner').value.trim(),action:$('edit-action').value,status:$('edit-status').value};if(!changes.activity){showSyncToast('Escribe una actividad');return}if(changes.status==='done'&&!changes.last){showSyncToast('Para marcarla como realizada indica la fecha');return}const check={...r,next:changes.next,status:changes.status};if(changes.status==='done'&&isOverdue(check)){showSyncToast('Una actividad vencida solo puede estar pendiente o en proceso');return}const columns={activity:1,category:2,frequency:3,last:4,next:5,owner:7,action:10,status:12};if(isNew){r.serverRow=Math.max(1,...centerRows.map(row=>row.serverRow||1))+1;centerRows.push(r)}const requests=[];Object.entries(changes).forEach(([field,value])=>{if(!isNew&&r[field]===value)return;r[field]=value;if(r.serverRow)requests.push(kurroRequest({api:'updateCell',fileId:'1AiIsFZCyZVp4ERTi0ExreV10StjayEw9tLWv4W21foQ',sheetName:'Registro Maestro',row:r.serverRow,column:columns[field],value:field==='status'?(value==='done'?'REALIZADO':value==='process'?'EN PROCESO':'PENDIENTE'):value}))});saveData();renderCenter();closeCenterEditor();if(requests.length){showSyncToast(isNew?'Añadiendo acción…':'Guardando cambios…');remoteWrite(Promise.all(requests)).then(()=>loadRemoteData()).then(()=>showSyncToast(isNew?'Acción añadida':'Cambios guardados')).catch(()=>showSyncToast('No se pudo guardar el cambio'))}}
const saveButton=$('save-center-editor');if(saveButton){const replacement=saveButton.cloneNode(true);saveButton.replaceWith(replacement);replacement.addEventListener('click',saveCenterEditorFlexible)}
const frequencyField=$('edit-frequency');frequencyField?.addEventListener('change',()=>{$('edit-next').dataset.manual='false';legacyNextPreview()});$('edit-last')?.addEventListener('change',()=>{$('edit-next').dataset.manual='false';legacyNextPreview()});
function renderAttention(){const panel=$('attention-panel');if(!panel)return;const overdue=centerRows.filter(isOverdue).length,soon=centerRows.filter(r=>{if(!r.next||isOverdue(r))return false;const p=r.next.split('/');return (new Date(`${p[2]}-${p[1]}-${p[0]}T23:59:59`)-new Date())<=30*86400000}).length,process=centerRows.filter(r=>effectiveStatus(r)==='process').length,noDate=centerRows.filter(r=>!r.next&&effectiveStatus(r)!=='done').length;panel.innerHTML=`<button class="attention-card alert" onclick="focusCenterState('overdue')"><strong>${overdue}</strong><small>Vencidas · revisar</small></button><button class="attention-card" onclick="focusCenterState('soon')"><strong>${soon}</strong><small>Próximas en 30 días</small></button><button class="attention-card" onclick="focusCenterState('process')"><strong>${process}</strong><small>En proceso</small></button><button class="attention-card" onclick="focusCenterState('nodate')"><strong>${noDate}</strong><small>Sin fecha definida</small></button>`}
function focusCenterState(kind){$('center-status').value='all';$('center-search').value='';window.centerQuickFilter=kind;renderCenter()}
function applyCenterQuickFilter(){const kind=window.centerQuickFilter;if(!kind)return;const byActivity=new Map(centerRows.map(r=>[r.activity,r]));document.querySelectorAll('#center-table tr').forEach(row=>{const r=byActivity.get(row.children[0]?.textContent.trim());let show=true;if(r){if(kind==='overdue')show=isOverdue(r);else if(kind==='process')show=effectiveStatus(r)==='process';else if(kind==='nodate')show=!r.next&&effectiveStatus(r)!=='done';else if(kind==='soon')show=!!r.next&&!isOverdue(r)&&((new Date(r.next.split('/').reverse().join('-')+'T23:59:59')-new Date())<=30*86400000)}row.style.display=show?'':'none'});const visible=[...document.querySelectorAll('#center-table tr')].filter(r=>r.style.display!=='none').length;$('center-count').textContent=`${visible} registros`}
const renderCenterWithAttention=renderCenter;renderCenter=function(){renderCenterWithAttention();renderAttention();applyCenterQuickFilter()};renderCenter();

let pendingEditorIndex=-1;
function pendingDateForEditor(value){const p=String(value||'').split('/');return p.length===3?`${p[2]}-${p[1].padStart(2,'0')}-${p[0].padStart(2,'0')}`:''}
function pendingDateFromEditor(value){const p=String(value||'').split('-');return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:''}
function openPendingEditor(index=-1){pendingEditorIndex=index;$('pending-edit-text').value=index<0?'':pendingRows[index].text||'';$('pending-edit-person').value=index<0?(window.person==='Properval'?'Properval':'Miguel'):pendingRows[index].person;$('pending-edit-priority').value=index<0?'NORMAL':pendingRows[index].priority||'NORMAL';$('pending-edit-status').value=index<0?'PENDIENTE':pendingRows[index].status||'PENDIENTE';$('pending-edit-date').value=index<0?'':pendingDateForEditor(pendingRows[index].date);$('pending-edit-comments').value=index<0?'':pendingRows[index].comments||'';$('pending-editor-title').textContent=index<0?'Nuevo pendiente':'Editar pendiente';$('pending-editor').classList.add('open');$('pending-editor').setAttribute('aria-hidden','false')}
function closePendingEditor(){$('pending-editor').classList.remove('open');$('pending-editor').setAttribute('aria-hidden','true');pendingEditorIndex=-1}
async function savePendingEditor(){const text=$('pending-edit-text').value.trim();if(!text){showSyncToast('Escribe el pendiente');return}const person=$('pending-edit-person').value,priority=$('pending-edit-priority').value,status=$('pending-edit-status').value,date=$('pending-edit-date').value?pendingDateFromEditor($('pending-edit-date').value):'',comments=$('pending-edit-comments').value;const isNew=pendingEditorIndex<0;let r=isNew?{person,status,text,priority,date,updated:formatDate(new Date()),comments}:pendingRows[pendingEditorIndex];if(isNew){const fileId=KURRO_SOURCE_ID;r.fileId=fileId;r.serverRow=Math.max(1,...pendingRows.filter(x=>x.fileId===fileId).map(x=>x.serverRow||1))+1;pendingRows.push(r)}Object.assign(r,{person,status,text,priority,date,comments,updated:formatDate(new Date())});saveData();renderPending();closePendingEditor();showSyncToast(isNew?'Añadiendo pendiente…':'Guardando pendiente…');const fields={person,status,task:text,priority,target:date,updated:r.updated,comments};try{await remoteWrite(Promise.all(Object.entries(fields).map(([field,value])=>kurroRequest({api:'updatePending',fileId:r.fileId,row:r.serverRow,field,value}))));await loadRemoteData();showSyncToast(isNew?'Pendiente añadido':'Pendiente guardado')}catch(e){showSyncToast('No se pudo guardar el pendiente')}}
const basePendingFieldHandler=updatePendingField;updatePendingField=function(index,field,value){const r=pendingRows[index];if(!r)return;const serverField=field==='date'?'target':field;r[field]=value;if(field==='status'&&value==='REALIZADO')r.closed=formatDate(new Date());r.updated=formatDate(new Date());saveData();if(r.fileId&&r.serverRow){remoteWrite(Promise.all([kurroRequest({api:'updatePending',fileId:r.fileId,row:r.serverRow,field:serverField,value}),serverField!=='updated'?kurroRequest({api:'updatePending',fileId:r.fileId,row:r.serverRow,field:'updated',value:r.updated}):Promise.resolve()]).catch(()=>{}))}renderPending()};
renderPending=function(){const q=($('pending-search').value||'').toLowerCase(),person=window.person||'all',priority=$('pending-priority').value,state=$('pending-status').value;const rows=pendingRows.filter(r=>(person==='all'||r.person===person)&&(priority==='all'||r.priority===priority)&&(state==='all'||r.status===state)&&[r.person,r.text,r.priority,r.comments].join(' ').toLowerCase().includes(q));$('pending-table').innerHTML=rows.length?rows.map(r=>{const i=pendingRows.indexOf(r);return `<tr><td><select class="status-select" aria-label="Estado de ${r.text}" onchange="updatePendingField(${i},'status',this.value)"><option ${r.status==='PENDIENTE'?'selected':''}>PENDIENTE</option><option ${r.status==='REALIZADO'?'selected':''}>REALIZADO</option></select></td><td>${r.text}</td><td><strong>${r.person}</strong></td><td><select class="status-select" aria-label="Prioridad de ${r.text}" onchange="updatePendingField(${i},'priority',this.value)"><option ${r.priority==='NORMAL'?'selected':''}>NORMAL</option><option ${r.priority==='ALTA'?'selected':''}>ALTA</option></select></td><td class="date"><input class="pending-date" type="date" aria-label="Fecha objetivo de ${r.text}" value="${pendingDateForEditor(r.date)}" onchange="updatePendingField(${i},'date',pendingDateFromEditor(this.value))"></td><td class="date">${r.updated||'<span class="muted">Sin fecha</span>'}</td><td><textarea class="comment-input" rows="2" placeholder="Añadir comentario" onchange="updatePendingField(${i},'comments',this.value)">${r.comments||''}</textarea></td><td><div class="pending-person"><button class="done-btn" onclick="updatePendingField(${i},'status','REALIZADO')" ${r.status==='REALIZADO'?'disabled':''}>Hecho</button><button class="edit-btn" onclick="openPendingEditor(${i})">Editar</button></div></td></tr>`}).join(''):`<tr><td colspan="8" class="empty">No hay resultados con estos filtros.</td></tr>`;$('pending-heading').textContent=person==='all'?'Todos mis pendientes':`Pendientes con ${person}`;$('pending-count').textContent=`${rows.length} registros`};
function updateEditorNextPreview(){const date=$('edit-last')?.value,frequency=$('edit-frequency')?.value==='custom'?$('edit-frequency-custom')?.value:$('edit-frequency')?.value;const next=date&&frequency?nextDate(date,frequency):null;if($('edit-next'))$('edit-next').value=next?dateForEditor(formatDate(next)):''}
document.querySelector('[data-new-pending]')?.addEventListener('click',()=>openPendingEditor());document.querySelectorAll('[data-close-pending]').forEach(b=>b.addEventListener('click',closePendingEditor));$('save-pending-editor')?.addEventListener('click',savePendingEditor);$('edit-last')?.addEventListener('change',updateEditorNextPreview);$('edit-frequency')?.addEventListener('change',updateEditorNextPreview);$('edit-frequency-custom')?.addEventListener('input',updateEditorNextPreview);renderPending();
// Sincronización con Google Sheets para la versión web pública.
const KURRO_SOURCE_ID='1AiIsFZCyZVp4ERTi0ExreV10StjayEw9tLWv4W21foQ';
const KURRO_API=(window.location.hostname==='script.google.com'||window.location.hostname.endsWith('.googleusercontent.com'))?window.location.origin+window.location.pathname:'https://script.google.com/macros/s/AKfycbz9CHAxNnfG0PBYIO1CHcUlbOLXh6noYYYOc6P6coo7576GKreW0qMdkZJecbdT1SwMOw/exec';
const KURRO_SHEET='https://docs.google.com/spreadsheets/d/'+KURRO_SOURCE_ID+'/gviz/tq';
function kurroRequest(params){return new Promise((resolve,reject)=>{const callback='kurro_'+Date.now()+'_'+Math.random().toString(36).slice(2),script=document.createElement('script');let settled=false,expired=false;const finish=(fn,value)=>{if(settled&&!expired)return;settled=true;expired=false;clearTimeout(timer);delete window[callback];script.remove();fn(value)};const timer=setTimeout(()=>{settled=true;expired=true;reject(new Error('Tiempo de espera agotado'));setTimeout(()=>{delete window[callback];script.remove()},60000)},30000);window[callback]=data=>{if(expired)return;if(data?.ok)finish(resolve,data.result);else finish(reject,new Error('Respuesta no válida'))};script.onerror=()=>{if(!expired)finish(reject,new Error('No se pudo conectar'))};script.src=KURRO_API+'?'+new URLSearchParams({...params,callback,_:Date.now()}).toString();document.body.appendChild(script)})}
function gvizRequest(sheet){return new Promise((resolve,reject)=>{const cb='gviz_'+Date.now()+'_'+Math.random().toString(36).slice(2),script=document.createElement('script');let settled=false;const finish=(fn,value)=>{if(settled)return;settled=true;clearTimeout(timer);delete window[cb];script.remove();fn(value)};const timer=setTimeout(()=>finish(reject,new Error('Lectura directa agotada')),12000);const receive=payload=>{const table=payload?.table||payload;if(!table?.cols||!table?.rows)return finish(reject,new Error('Formato de hoja no válido'));const values=[table.cols.map(c=>c.label||'')];table.rows.forEach(row=>values.push((row.c||[]).map(cell=>cell?.f??cell?.v??'')));finish(resolve,values)};window[cb]=receive;window.google=window.google||{};window.google.visualization=window.google.visualization||{};window.google.visualization.Query=window.google.visualization.Query||{};window.google.visualization.Query.setResponse=receive;script.onerror=()=>finish(reject,new Error('No se pudo leer Google Sheets'));script.src=KURRO_SHEET+'?'+new URLSearchParams({sheet,tqx:'out:json;responseHandler:'+cb,_:Date.now()});document.body.appendChild(script)})}
async function loadGvizData(){const [planning,pending,clients]=await Promise.all([gvizRequest('Registro Maestro'),gvizRequest('Seguimientos'),gvizRequest('Clientes')]);const header=pending[0]||[],personCol=header.indexOf('Persona o empresa');const forPerson=person=>[pending[0],...pending.slice(1).filter(row=>String(row[personCol]||'').trim()===person)];return{planning:{id:KURRO_SOURCE_ID,name:'Registro Maestro',values:planning},miguel:{id:KURRO_SOURCE_ID,name:'Seguimientos',values:forPerson('Miguel')},properval:{id:KURRO_SOURCE_ID,name:'Seguimientos',values:forPerson('Properval')},clients:{id:KURRO_SOURCE_ID,name:'Clientes',values:clients}}}
function setDataAlert(message){const alert=$('data-alert');if(!alert)return;alert.textContent=message;alert.hidden=!message}
function remotePlanningRow(row,index){const y=String(row[11]||'').trim().toUpperCase();let status=/REALIZADO|ACEPTADO|HECHO/.test(y)?'done':/EN PROCESO|PROCESO/.test(y)?'process':'open';return{activity:row[0]||'',category:row[1]||'Otros',frequency:row[2]||'',last:normalizeSheetDate(row[3]),next:normalizeSheetDate(row[4]),owner:row[5]||'',status,action:row[9]||'',serverRow:index+2}}
function remotePendingRow(row,index,person,fileId){return{person,status:String(row[0]||'PENDIENTE').toUpperCase(),comments:row[1]||'',text:row[2]||'',priority:String(row[3]||'NORMAL').toUpperCase(),date:normalizeSheetDate(row[4]),updated:normalizeSheetDate(row[5]),closed:normalizeSheetDate(row[6]),serverRow:Number(row[7]||index+2),fileId}}
async function loadRemoteData(){let error=null;for(let attempt=0;attempt<3;attempt++){try{let data;try{data=await kurroRequest({api:'data'})}catch(primaryError){error=primaryError;data=await loadGvizData()}window.kurroLastData=data;if(data?.planning?.values?.length){const planningRows=data.planning.values.slice(1).map((row,index)=>({row,index})).filter(x=>x.row.some(Boolean)).map(x=>remotePlanningRow(x.row,x.index));centerRows.splice(0,centerRows.length,...planningRows)}const p=[];for(const source of [{data:data?.miguel,person:'Miguel'},{data:data?.properval,person:'Properval'}])if(source.data?.values?.length)source.data.values.slice(1).filter(r=>r.some(Boolean)).forEach((r,i)=>p.push(remotePendingRow(r,i,source.person,source.data.id)));pendingRows.splice(0,pendingRows.length,...p);saveData();refreshKURROMetrics();renderCenter();renderPending();if($('sync-label'))$('sync-label').textContent='Sincronizado';setDataAlert('');return true}catch(e){error=e;if(attempt<2)await new Promise(r=>setTimeout(r,1800))}}refreshKURROMetrics();renderCenter();renderPending();const hasCachedData=Boolean(centerRows.length||pendingRows.length);if($('sync-label'))$('sync-label').textContent=hasCachedData?'Sin conexión · últimos datos':'No se han podido cargar los datos';setDataAlert(hasCachedData?'Sin conexión: se muestran los últimos datos guardados en este dispositivo.':'No se pueden cargar los datos. Comprueba que la red permite acceder a Google Sheets y pulsa «Actualizar».');if(!hasCachedData){showSyncToast('No se pudieron cargar los datos');setTimeout(()=>{if(!centerRows.length&&!pendingRows.length)loadRemoteData()},5000)}console.warn('No se pudo actualizar la vista',error);return false}
let kurroPendingWrites=0;
let kurroRefreshInFlight=false;
function remoteWrite(request){kurroPendingWrites++;return request.finally(()=>{kurroPendingWrites--})}
function isEditingKURRO(){const active=document.activeElement;return active&&(['INPUT','TEXTAREA','SELECT'].includes(active.tagName)||active.isContentEditable)}
function showSyncToast(message){const toast=$('toast');if(!toast)return;toast.textContent=message;toast.classList.add('show');clearTimeout(window.kurroToastTimer);window.kurroToastTimer=setTimeout(()=>toast.classList.remove('show'),2200)}
function refreshKURROMetrics(){if($('center-metrics'))$('center-metrics').innerHTML=metric('Actividades registradas',centerRows.length,'Registro maestro')+metric('Pendientes de centro',centerRows.filter(r=>effectiveStatus(r)==='open').length,'Requieren seguimiento',true)+metric('En proceso',centerRows.filter(r=>effectiveStatus(r)==='process').length,'Acciones abiertas')+metric('Próximas revisiones',centerRows.filter(r=>r.next).length,'Con fecha definida');if($('pending-metrics'))$('pending-metrics').innerHTML=metric('Pendientes totales',pendingRows.filter(r=>r.status!=='REALIZADO').length,'Miguel + Properval')+metric('Con Miguel',pendingRows.filter(r=>r.person==='Miguel'&&r.status!=='REALIZADO').length,'Seguimiento activo')+metric('Con Properval',pendingRows.filter(r=>r.person==='Properval'&&r.status!=='REALIZADO').length,'Seguimiento activo')+metric('Con fecha objetivo',pendingRows.filter(r=>r.date&&r.status!=='REALIZADO').length,'Para priorizar')}
async function refreshKURROFromSheets(silent=false){if(kurroRefreshInFlight||kurroPendingWrites||isEditingKURRO())return;kurroRefreshInFlight=true;try{await loadRemoteData();if(!silent)showSyncToast('Datos actualizados desde Google Sheets')}finally{kurroRefreshInFlight=false}}
setInterval(()=>{if(document.visibilityState==='visible')refreshKURROFromSheets(true)},30000);
window.addEventListener('focus',()=>refreshKURROFromSheets(true));
document.querySelector('[data-refresh]')?.addEventListener('click',async()=>{const button=document.querySelector('[data-refresh]');button?.classList.add('busy');if($('sync-label'))$('sync-label').textContent='Actualizando…';await refreshKURROFromSheets(false);if($('sync-label'))$('sync-label').textContent='Sincronizado';button?.classList.remove('busy')});
const localUpdateCenterField=updateCenterField;updateCenterField=function(index,field,value){const r=centerRows[index];if(field==='status'&&value==='done'&&isOverdue(r)){r.status='process';renderCenter();return}r[field]=value;saveData();if(r.serverRow){const col=field==='owner'?7:field==='action'?10:field==='status'?12:null;if(col)remoteWrite(kurroRequest({api:'updateCell',fileId:'1AiIsFZCyZVp4ERTi0ExreV10StjayEw9tLWv4W21foQ',sheetName:'Registro Maestro',row:r.serverRow,column:col,value:field==='status'?(value==='done'?'REALIZADO':value==='process'?'EN PROCESO':'PENDIENTE'):value}).catch(()=>{}))}renderCenter()};
let centerEditorIndex=null;
function dateForEditor(value){const p=String(value||'').split('/');return p.length===3?`${p[2]}-${p[1].padStart(2,'0')}-${p[0].padStart(2,'0')}`:''}
function dateFromEditor(value){const p=String(value||'').split('-');return p.length===3?`${p[2]}/${p[1]}/${p[0]}`:''}
function frequencyChoice(value){const f=String(value||'').toLowerCase();if(f.includes('seman'))return'Semanal';if(f.includes('bimes'))return'Bimestral';if(f.includes('trimes'))return'Trimestral';if(f.includes('semes'))return'Semestral';if(f.includes('mens'))return'Mensual';if(f.includes('5 años'))return'Cada 5 años';if(f.includes('3 años'))return'Cada 3 años';if(f.includes('anual')||f.includes('1 año'))return'Anual';if(f.includes('cuando aplique'))return'Cuando aplique';if(f.includes('cambio'))return'Según cambios';if(!f||f.includes('sin periodicidad')||f.includes('no periódica'))return'Sin periodicidad';return'custom'}
function openCenterEditor(index){const r=centerRows[index];if(!r)return;centerEditorIndex=index;[['activity',r.activity],['category',r.category],['owner',r.owner],['action',r.action]].forEach(([key,value])=>{const field=$(`edit-${key}`);if(field)field.value=value||''});const choice=frequencyChoice(r.frequency);$('edit-frequency').value=choice;$('edit-frequency-custom').value=choice==='custom'?(r.frequency||''):'';$('edit-frequency-custom').hidden=choice!=='custom';$('edit-last').value=dateForEditor(r.last);$('edit-next').value=dateForEditor(r.next);$('edit-status').value=effectiveStatus(r);$('delete-center-editor').hidden=false;$('editor-title').textContent=isOverdue(r)?'Registrar seguimiento':'Editar actividad';$('edit-last-label').textContent=isOverdue(r)?'Fecha de actuación':'Última revisión';$('save-center-editor').textContent=isOverdue(r)?'Guardar seguimiento':'Guardar cambios';$('center-editor').classList.add('open');$('center-editor').setAttribute('aria-hidden','false')}
function openNewCenterEditor(){centerEditorIndex=-1;[['activity',''],['category',''],['owner',''],['action','']].forEach(([key,value])=>{$(`edit-${key}`).value=value});$('edit-frequency').value='Sin periodicidad';$('edit-frequency-custom').value='';$('edit-frequency-custom').hidden=true;$('edit-last').value='';$('edit-next').value='';$('edit-status').value='open';$('delete-center-editor').hidden=true;$('editor-title').textContent='Nueva acción';$('edit-last-label').textContent='Última revisión';$('save-center-editor').textContent='Guardar cambios';$('center-editor').classList.add('open');$('center-editor').setAttribute('aria-hidden','false')}
function closeCenterEditor(){$('center-editor').classList.remove('open');$('center-editor').setAttribute('aria-hidden','true');centerEditorIndex=null}
async function saveCenterEditor(){const index=centerEditorIndex,isNew=index===-1,r=isNew?{}:centerRows[index];if(!r)return;const frequency=$('edit-frequency').value==='custom'?$('edit-frequency-custom').value.trim():$('edit-frequency').value;const last=$('edit-last').value?dateFromEditor($('edit-last').value):'';const calculated=last&&frequency?nextDate($('edit-last').value,frequency):null;const changes={activity:$('edit-activity').value.trim(),category:$('edit-category').value.trim()||'Otros',frequency,last,next:calculated?formatDate(calculated):'',owner:$('edit-owner').value.trim(),action:$('edit-action').value,status:$('edit-status').value};if(!changes.activity){showSyncToast('Escribe una actividad');return}if(changes.status==='done'&&!changes.last){showSyncToast('Para marcarla como realizada indica la fecha');return}const check={...r,next:changes.next,status:changes.status};if(changes.status==='done'&&isOverdue(check)){showSyncToast('Una actividad vencida solo puede estar pendiente o en proceso');return}const columns={activity:1,category:2,frequency:3,last:4,next:5,owner:7,action:10,status:12};if(isNew){r.serverRow=Math.max(1,...centerRows.map(row=>row.serverRow||1))+1;centerRows.push(r)}const requests=[];Object.entries(changes).forEach(([field,value])=>{if(!isNew&&r[field]===value)return;r[field]=value;if(r.serverRow)requests.push(kurroRequest({api:'updateCell',fileId:'1AiIsFZCyZVp4ERTi0ExreV10StjayEw9tLWv4W21foQ',sheetName:'Registro Maestro',row:r.serverRow,column:columns[field],value:field==='status'?(value==='done'?'REALIZADO':value==='process'?'EN PROCESO':'PENDIENTE'):value}))});saveData();renderCenter();closeCenterEditor();if(requests.length){showSyncToast(isNew?'Añadiendo acción…':'Guardando cambios…');try{await remoteWrite(Promise.all(requests));await loadRemoteData();showSyncToast(isNew?'Acción añadida':'Cambios guardados')}catch(e){showSyncToast('No se pudo guardar el cambio')}}}
document.querySelectorAll('[data-close-editor]').forEach(button=>button.addEventListener('click',closeCenterEditor));$('edit-frequency')?.addEventListener('change',()=>{$('edit-frequency-custom').hidden=$('edit-frequency').value!=='custom'});$('save-center-editor')?.addEventListener('click',saveCenterEditor);
async function deleteCenterEditor(){const index=centerEditorIndex,r=centerRows[index];if(!r||!r.serverRow||!confirm('¿Quieres eliminar esta actividad?'))return;const requests=[];for(let column=1;column<=12;column++)requests.push(kurroRequest({api:'updateCell',fileId:'1AiIsFZCyZVp4ERTi0ExreV10StjayEw9tLWv4W21foQ',sheetName:'Registro Maestro',row:r.serverRow,column,value:''}));try{await remoteWrite(Promise.all(requests));closeCenterEditor();await loadRemoteData();showSyncToast('Actividad eliminada')}catch(e){showSyncToast('No se pudo eliminar la actividad')}}
$('[data-new-center]')?.addEventListener('click',openNewCenterEditor);$('delete-center-editor')?.addEventListener('click',deleteCenterEditor);
const localMarkCenterDone=markCenterDone;markCenterDone=function(index){const r=centerRows[index],input=$(`done-date-${index}`);if(!input?.value||isOverdue(r)){localMarkCenterDone(index);return}if(r.serverRow)remoteWrite(kurroRequest({api:'markPlanningDone',row:r.serverRow,dateText:input.value})).then(()=>loadRemoteData()).catch(()=>localMarkCenterDone(index));else localMarkCenterDone(index)};
const localUpdatePendingField=updatePendingField;updatePendingField=function(index,field,value){const r=pendingRows[index];r[field]=value;saveData();if(r.fileId&&r.serverRow){remoteWrite(kurroRequest({api:'updatePending',fileId:r.fileId,row:r.serverRow,field,value}).catch(()=>{}))}renderPending()};
const localMarkPendingDone=markPendingDone;markPendingDone=function(index){const r=pendingRows[index];r.status='REALIZADO';if(r.fileId&&r.serverRow)remoteWrite(kurroRequest({api:'updatePending',fileId:r.fileId,row:r.serverRow,field:'status',value:'REALIZADO'})).then(()=>loadRemoteData()).catch(()=>localMarkPendingDone(index));else localMarkPendingDone(index)};
// Garantiza que la acción Editar permanezca visible aunque otra rutina
// vuelva a pintar la tabla de pendientes.
const kurroRenderPendingWithEdit = renderPending;
renderPending = function(){
  kurroRenderPendingWithEdit();
  document.querySelectorAll('#pending-table tr').forEach(row=>{
    const actionCell=row.lastElementChild;
    if(!actionCell || actionCell.querySelector('.edit-btn')) return;
    const text=row.children[1]?.textContent.trim()||'';
    const person=row.children[2]?.textContent.trim()||'';
    const index=pendingRows.findIndex(item=>item.text===text&&item.person===person);
    if(index<0) return;
    const button=document.createElement('button');
    button.className='edit-btn pending-edit-visible';
    button.type='button';
    button.textContent='Editar';
    button.onclick=()=>openPendingEditor(index);
    actionCell.appendChild(button);
  });
};
// CLIENTES placeholder integration.
const CLIENTS_FILE_ID=KURRO_SOURCE_ID;
let clientRows=[],clientEditorIndex=-1,clientsLoading=true;
function clientDateForEditor(v){const p=String(v||'').split('/');return p.length===3?p[2]+'-'+p[1].padStart(2,'0')+'-'+p[0].padStart(2,'0'):''}
function clientDateFromEditor(v){const p=String(v||'').split('-');return p.length===3?p[2]+'/'+p[1]+'/'+p[0]:''}
function clientOptions(){const l=mergedKurroLists();return [...new Set([...(l.client||[]),...clientRows.map(r=>r.client)].map(v=>String(v||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es'))}
function refreshClientOptions(){const s=$('client-edit-client');if(!s)return;const v=s.value;s.innerHTML='<option value="">Sin asignar</option>'+clientOptions().map(x=>'<option>'+x+'</option>').join('');if(v)s.value=v}
function saveClientData(){try{localStorage.setItem('kurro-clients-v1',JSON.stringify(clientRows))}catch(e){}}
function loadClientData(){try{const cached=JSON.parse(localStorage.getItem('kurro-clients-v1')||'null');if(!Array.isArray(cached))return false;clientRows.splice(0,clientRows.length,...cached.filter(r=>r&&typeof r==='object'));clientsLoading=clientRows.length===0;return clientRows.length>0}catch(e){return false}}
function renderClientMetrics(){const open=clientRows.filter(r=>r.status!=='REALIZADO');$('client-metrics').innerHTML=metric('Pendientes activos',open.length,'Seguimiento con clientes',true)+metric('En proceso',open.filter(r=>r.status==='EN PROCESO').length,'Gestiones abiertas')+metric('Alta prioridad',open.filter(r=>r.priority==='ALTA').length,'Para atender')+metric('Con fecha objetivo',open.filter(r=>r.date).length,'Para organizar')}
function updateClientField(i,f,v){const r=clientRows[i];if(!r)return;r[f]=v;r.updated=formatDate(new Date());saveClientData();renderClients();if(r.serverRow)remoteWrite(kurroRequest({api:'updateClient',fileId:CLIENTS_FILE_ID,row:r.serverRow,field:f==='date'?'target':f,value:v}).catch(()=>{}))}
function renderClients(){const q=($('client-search')?.value||'').toLowerCase(),pr=$('client-priority')?.value||'all',st=$('client-status')?.value||'PENDIENTE',rows=clientRows.filter(r=>(pr==='all'||r.priority===pr)&&(st==='all'||r.status===st)&&[r.client,r.contact,r.text,r.comments].join(' ').toLowerCase().includes(q));if(clientsLoading&&!clientRows.length){$('client-table').innerHTML='<tr><td colspan="9" class="empty">Cargando clientes desde Google Sheets…</td></tr>';$('client-count').textContent='Cargando…';return}$('client-table').innerHTML=rows.length?rows.map(r=>{const i=clientRows.indexOf(r);return '<tr><td><select class="status-select" onchange="updateClientField('+i+',\'status\',this.value)"><option '+(r.status==='PENDIENTE'?'selected':'')+'>PENDIENTE</option><option '+(r.status==='EN PROCESO'?'selected':'')+'>EN PROCESO</option><option '+(r.status==='REALIZADO'?'selected':'')+'>REALIZADO</option></select></td><td><strong>'+(r.client||'<span class=muted>Sin asignar</span>')+'</strong></td><td>'+(r.contact||'<span class=muted>Sin contacto</span>')+'</td><td>'+(r.text||'')+'</td><td><select class="status-select" onchange="updateClientField('+i+',\'priority\',this.value)"><option '+(r.priority==='NORMAL'?'selected':'')+'>NORMAL</option><option '+(r.priority==='ALTA'?'selected':'')+'>ALTA</option></select></td><td class="date"><input class="pending-date" type="date" value="'+clientDateForEditor(r.date)+'" onchange="updateClientField('+i+',\'date\',clientDateFromEditor(this.value))"></td><td class="date">'+(r.updated||'<span class=muted>Sin fecha</span>')+'</td><td><textarea class="comment-input" rows="2" placeholder="Añadir comentario" onchange="updateClientField('+i+',\'comments\',this.value)">'+(r.comments||'')+'</textarea></td><td><button class="done-btn" onclick="updateClientField('+i+',\'status\',\'REALIZADO\')" '+(r.status==='REALIZADO'?'disabled':'')+'>Hecho</button> <button class="edit-btn" onclick="openClientEditor('+i+')">Editar</button></td></tr>'}).join(''):'<tr><td colspan="9" class="empty">No hay pendientes con estos filtros. Pulsa «Nuevo pendiente» para añadir el primero.</td></tr>';$('client-count').textContent=rows.length+' registros';renderClientMetrics()}
function openClientEditor(i=-1){clientEditorIndex=i;const r=i<0?{}:clientRows[i];refreshClientOptions();$('client-edit-client').value=r.client||'';$('client-edit-contact').value=r.contact||'';$('client-edit-text').value=r.text||'';$('client-edit-priority').value=r.priority||'NORMAL';$('client-edit-status').value=r.status||'PENDIENTE';$('client-edit-date').value=clientDateForEditor(r.date);$('client-edit-comments').value=r.comments||'';$('client-editor-title').textContent=i<0?'Nuevo pendiente':'Editar pendiente';$('client-editor').classList.add('open');$('client-editor').setAttribute('aria-hidden','false')}
function closeClientEditor(){$('client-editor').classList.remove('open');$('client-editor').setAttribute('aria-hidden','true');clientEditorIndex=-1}
async function saveClientEditor(){const text=$('client-edit-text').value.trim();if(!text){showSyncToast('Escribe el pendiente');return}const n=clientEditorIndex<0,r=n?{}:clientRows[clientEditorIndex];Object.assign(r,{client:$('client-edit-client').value.trim(),contact:$('client-edit-contact').value.trim(),text,priority:$('client-edit-priority').value,status:$('client-edit-status').value,date:$('client-edit-date').value?clientDateFromEditor($('client-edit-date').value):'',updated:formatDate(new Date()),comments:$('client-edit-comments').value});if(n){r.serverRow=Math.max(1,...clientRows.map(x=>x.serverRow||1))+1;r.fileId=CLIENTS_FILE_ID;clientRows.push(r)}saveClientData();renderClients();closeClientEditor();showSyncToast(n?'Añadiendo pendiente…':'Guardando pendiente…');try{await remoteWrite(Promise.all(Object.entries({status:r.status,client:r.client,contact:r.contact,task:r.text,priority:r.priority,target:r.date,updated:r.updated,comments:r.comments}).map(([field,value])=>kurroRequest({api:'updateClient',fileId:CLIENTS_FILE_ID,row:r.serverRow,field,value}))));showSyncToast(n?'Pendiente añadido':'Pendiente guardado')}catch(e){showSyncToast('Guardado local; falta publicar la conexión de clientes')}}
function remoteClientRow(row,i){return{status:String(row[0]||'PENDIENTE').toUpperCase(),client:row[1]||'',contact:row[2]||'',text:row[3]||'',priority:String(row[4]||'NORMAL').toUpperCase(),date:row[5]||'',updated:row[6]||'',comments:row[7]||'',closed:row[8]||'',serverRow:i+2,fileId:CLIENTS_FILE_ID}}
function loadRemoteClients(d){if(!d?.values?.length)return;clientRows=d.values.slice(1).filter(r=>r.some(Boolean)).map((r,i)=>remoteClientRow(r,i));clientsLoading=false;saveClientData();renderClients()}
document.querySelector('[data-new-client]')?.addEventListener('click',()=>openClientEditor());document.querySelectorAll('[data-close-client]').forEach(b=>b.addEventListener('click',closeClientEditor));$('save-client-editor')?.addEventListener('click',saveClientEditor);$('add-client-option')?.addEventListener('click',()=>{const v=prompt('Nombre del nuevo cliente');if(!v?.trim())return;const l=savedKurroLists();l.client=[...(l.client||[]),v.trim()];saveKurroLists(l);refreshClientOptions();$('client-edit-client').value=v.trim()});['client-search','client-priority','client-status'].forEach(id=>$(id)?.addEventListener('input',renderClients));loadClientData();refreshClientOptions();renderClients();
const previousClientAwareLoad=loadRemoteData;loadRemoteData=async function(){const directClients=gvizRequest('Clientes').catch(()=>null);await previousClientAwareLoad();try{const d=window.kurroLastData||await kurroRequest({api:'data'});const clientValues=d?.clients?.values||[];const hasClientRows=clientValues.slice(1).some(row=>row.some(Boolean));const clients=hasClientRows?d.clients:(await directClients)||{id:KURRO_SOURCE_ID,name:'Clientes',values:[]};loadRemoteClients(clients);const c=await kurroRequest({api:'config'});saveRemoteKurroLists(c.values);refreshKurroPeopleOptions();refreshClientOptions()}catch(e){}};
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.view==='clients')$('page-title').textContent='Pendientes con clientes'}));
loadRemoteData();
async function deleteClientEditor(){const i=clientEditorIndex,r=clientRows[i];if(!r||!confirm('¿Quieres eliminar este pendiente?'))return;clientRows.splice(i,1);saveClientData();closeClientEditor();renderClients();if(r.serverRow){try{await remoteWrite(Promise.all(['status','client','contact','task','priority','target','updated','comments','closed'].map(field=>kurroRequest({api:'updateClient',fileId:CLIENTS_FILE_ID,row:r.serverRow,field,value:''}))))}catch(e){showSyncToast('Eliminado en esta vista; falta publicar la conexión')}}showSyncToast('Pendiente eliminado')}
$('delete-client-editor')?.addEventListener('click',deleteClientEditor);

// Todas las tablas usan una única acción de fila: Editar.
function removeExtraRowActions(){
  document.querySelectorAll('#center-table .done-btn,#pending-table .done-btn,#client-table .done-btn').forEach(button=>button.remove());
  document.querySelectorAll('table .row-actions input[type="date"]').forEach(input=>input.remove());
}
const renderCenterWithSingleAction=renderCenter;
renderCenter=()=>{renderCenterWithSingleAction();removeExtraRowActions()};
const renderPendingWithSingleAction=renderPending;
renderPending=()=>{renderPendingWithSingleAction();removeExtraRowActions()};
const renderClientsWithSingleAction=renderClients;
renderClients=()=>{renderClientsWithSingleAction();removeExtraRowActions()};
removeExtraRowActions();

// Cada entrada en Centro parte de su configuración operativa habitual.
// El estado elegido filtra la tabla, pero no debe quedarse pegado al cambiar de vista.
document.querySelectorAll('.nav-item').forEach(button=>button.addEventListener('click',()=>{
  if(button.dataset.view!=='center')return;
  $('center-search').value='';
  $('center-category').value='all';
  $('center-status').value='open';
  $('center-sort').value='next';
  window.centerQuickFilter=null;
  renderCenter();
}));

// Las tablas se consultan en modo lectura; los cambios se hacen desde Editar.
function harmonizeTableRows(tableId){
  const table=$(tableId); if(!table)return;
  table.querySelectorAll('tr').forEach(row=>{
    row.querySelectorAll('select,input[type="date"],textarea').forEach(control=>{
      const cell=control.closest('td'); if(!cell)return;
      const value=control.tagName==='SELECT'?control.options[control.selectedIndex]?.text:(control.value||'');
      const text=document.createElement('span');
      text.className='table-value';
      text.textContent=value||'Sin fecha';
      control.replaceWith(text);
    });
    row.querySelectorAll('.done-btn').forEach(button=>button.remove());
  });
}
const renderPendingHomogeneous=renderPending;
renderPending=function(){renderPendingHomogeneous();harmonizeTableRows('pending-table')};
const renderClientsHomogeneous=renderClients;
renderClients=function(){renderClientsHomogeneous();harmonizeTableRows('client-table')};
renderPending();
renderClients();

// Conserva la configuración de cada vista al navegar por la aplicación.
const VIEW_FILTERS_KEY='kurro-view-filters-v1';
const VIEW_FILTER_FIELDS={
  center:['center-search','center-category','center-status','center-sort'],
  pending:['pending-search','pending-priority','pending-status'],
  clients:['client-search','client-priority','client-status']
};
function readViewFilters(){try{return JSON.parse(localStorage.getItem(VIEW_FILTERS_KEY)||'{}')}catch(e){return {}}}
function saveViewFilters(view){
  const fields=VIEW_FILTER_FIELDS[view]; if(!fields)return;
  const all=readViewFilters(); all[view]=Object.fromEntries(fields.map(id=>[id,$(id)?.value||'']));
  try{localStorage.setItem(VIEW_FILTERS_KEY,JSON.stringify(all))}catch(e){}
}
function restoreViewFilters(view){
  const fields=VIEW_FILTER_FIELDS[view],saved=readViewFilters()[view]; if(!fields||!saved)return;
  fields.forEach(id=>{if($(id)&&saved[id]!==undefined)$(id).value=saved[id]});
  if(view==='pending')renderPending();
  if(view==='clients')renderClients();
  if(view==='center')renderCenter();
}
Object.keys(VIEW_FILTER_FIELDS).forEach(view=>VIEW_FILTER_FIELDS[view].forEach(id=>{
  $(id)?.addEventListener('input',()=>saveViewFilters(view));
  $(id)?.addEventListener('change',()=>saveViewFilters(view));
}));
document.querySelectorAll('.nav-item').forEach(button=>button.addEventListener('click',()=>setTimeout(()=>restoreViewFilters(button.dataset.view),0)));
Object.keys(VIEW_FILTER_FIELDS).forEach(restoreViewFilters);
