const centerRows = [
  {activity:'Revisión lavaojos de emergencia',category:'Almacén',frequency:'Semanal',last:'18/05/2026',next:'25/07/2026',owner:'Responsable centro',status:'done',action:'Avisado Propervall que no está todavía la puesta en marcha correcta'},
  {activity:'Limpieza Nave y cristales',category:'Almacén',frequency:'Bimestral',last:'31/08/2026',next:'31/10/2026',owner:'Responsable centro',status:'done',action:'REALIZADO'},
  {activity:'Exámenes de salud de los empleados',category:'Evaluación de Riesgos y Prevención',frequency:'1 año',last:'29/05/2025',next:'29/07/2026',owner:'SC / CVA',status:'done',action:'CONSEGUIR CERTIFICADO DE APTO'},
  {activity:'Cartel señalización plan de circulación y firmar recibido',category:'Línea provisional',frequency:'',last:'',next:'30/07/2026',owner:'',status:'open',action:'Pendiente de completar'},
  {activity:'Mantenimiento Preventivo del Portón',category:'Portón abatible',frequency:'Semestral',last:'14/02/2026',next:'28/08/2026',owner:'Responsable centro',status:'done',action:'Ver correo certificado Propervall (reclamado)'},
  {activity:'Limpieza oficinas y baños registro',category:'Almacén',frequency:'Mensual',last:'31/08/2026',next:'30/09/2026',owner:'Responsable centro',status:'done',action:'REALIZADO'},
  {activity:'Escalera - inspección visual',category:'Almacén',frequency:'Anual',last:'22/09/2025',next:'22/09/2026',owner:'Responsable centro',status:'done',action:'REALIZADO'},
  {activity:'Control de Plagas',category:'Almacén',frequency:'Trimestral',last:'04/06/2026',next:'04/10/2026',owner:'Anticymex',status:'done',action:'REALIZADO'},
  {activity:'PCI - extintores, BIE y sistema de detección',category:'PCI',frequency:'Trimestral',last:'07/07/2026',next:'07/10/2026',owner:'Administración / Responsable centro',status:'done',action:'REALIZADO'},
  {activity:'Procedimientos AP',category:'Calidad',frequency:'',last:'',next:'',owner:'SC / Calidad',status:'process',action:'EN PROCESO EHS'},
  {activity:'Simulacro de emergencia (documentado)',category:'Emergencias / MAUs',frequency:'Anual',last:'',next:'',owner:'Responsable centro / EHS',status:'open',action:'Enviado email Federico'},
  {activity:'CARA Evaluación de Riesgos por Agentes Químicos',category:'Evaluación de Riesgos y Prevención',frequency:'5 años',last:'',next:'',owner:'SC / EHS',status:'open',action:'PENDIENTE, EN PROCESO EHS, TERMINAR LISTADO DE PRODUCTOS QUÍMICOS'},
  {activity:'Formación CVA en carga/descarga de vehículos',category:'Formación',frequency:'Según CVA',last:'',next:'',owner:'SC / CVA',status:'open',action:'Reclamado a Antonio Royo'},
  {activity:'Apertura del centro de trabajo',category:'Legal / Licencias',frequency:'Única',last:'',next:'',owner:'SC / HR',status:'done',action:'Enviado email Miguel'},
  {activity:'ATEX - zona de carga de carretilla',category:'Legal / Licencias',frequency:'Revisión cuando haya cambios',last:'',next:'',owner:'EHS',status:'open',action:'Documento ATEX y actualización de planos pendientes por RISCAT. Hablar con Carles'},
  {activity:'Registro Sanitario',category:'Legal / Licencias',frequency:'',last:'',next:'',owner:'SC / EHS',status:'open',action:'Pendiente respuesta de la CAM'},
  {activity:'APCA',category:'Medio Ambiente',frequency:'Ver si aplica',last:'',next:'',owner:'SC / EHS (Carla Macedo)',status:'open',action:'PENDIENTE PLANIFICACIÓN'},
  {activity:'Licencia Autorización Ambiental',category:'Medio Ambiente',frequency:'Ver si aplica',last:'',next:'',owner:'SC / EHS (Carla Macedo)',status:'open',action:'PENDIENTE PLANIFICACIÓN'},
  {activity:'Productor de Residuos',category:'Medio Ambiente',frequency:'',last:'',next:'',owner:'SC / EHS (Carla Macedo)',status:'open',action:'Enviado email a Carla Macedo · PENDIENTE PLANIFICACIÓN'},
  {activity:'Ruido al exterior',category:'Medio Ambiente',frequency:'Ver si aplica',last:'',next:'',owner:'SC / EHS (Carla Macedo)',status:'open',action:'Enviado email a Carla Macedo · PENDIENTE PLANIFICACIÓN'},
  {activity:'RITE - Instalaciones térmicas (climatización)',category:'Legal / Licencias',frequency:'Revisión cuando haya cambios',last:'',next:'',owner:'EHS / SC',status:'done',action:'REALIZADO'},
  {activity:'Licencia de actividad (cambio de titularidad)',category:'Legal / Licencias',frequency:'',last:'',next:'',owner:'SC / HR',status:'done',action:'Enviado email Miguel · pedido cambio de titularidad'},
  {activity:'Registro de Establecimientos Industriales (REIC)',category:'Legal / Licencias',frequency:'',last:'',next:'',owner:'SC / HR',status:'done',action:'REALIZADO, pedido cambio de titularidad'},
  {activity:'Memoria Técnica',category:'Calidad',frequency:'',last:'01/05/2026',next:'',owner:'SC / Calidad',status:'done',action:'REALIZADO'},
  {activity:'Revisión carretilla elevadora LINDE E25',category:'Almacén',frequency:'500 horas en contrato',last:'30/03/2026',next:'',owner:'Responsable centro',status:'done',action:'REALIZADO'},
  {activity:'Carretilla elevadora - checklist diario',category:'Almacén',frequency:'Diario (Evaluación de Riesgos)',last:'',next:'',owner:'Operador carretilla',status:'done',action:'Lo hace RAUL MATESANZ y existe archivo físico'},
  {activity:'Prerrequisitos',category:'Calidad',frequency:'',last:'',next:'',owner:'SC / Calidad',status:'done',action:'REALIZADO'},
  {activity:'Jod Aids',category:'Descripción puesto de trabajo',frequency:'No periódica',last:'',next:'',owner:'SC / Dirección',status:'done',action:'REALIZADO'},
  {activity:'MAUs - revisión por cambios (personal/horario/instalación)',category:'Emergencias / MAUs',frequency:'Cuando aplique (MAUs)',last:'',next:'',owner:'Responsable del centro',status:'open',action:'Ver si hay que cambiar algo con los dewars'},
  {activity:'Informes higiénicos y ergonómicos, psicosociales',category:'Evaluación de Riesgos y Prevención',frequency:'Depende de resultados',last:'',next:'',owner:'SC / EHS',status:'open',action:'REALIZADO, PENDIENTE RESULTADOS'},
  {activity:'Curso básico de PRL',category:'Formación',frequency:'No periódica',last:'',next:'',owner:'SC / EHS',status:'done',action:'REALIZADO'},
  {activity:'Formación permisos de trabajo',category:'Formación',frequency:'No periódica',last:'',next:'',owner:'SC / EHS',status:'done',action:'Tengo que hacer alguno más'},
  {activity:'Registro Sanitario - respuesta de la CAM',category:'Legal / Licencias',frequency:'',last:'',next:'',owner:'SC / EHS',status:'open',action:'Pendiente respuesta de la CAM'},
  {activity:'PCI - Extintores portátiles, BIE y sistema de detección (anual)',category:'PCI',frequency:'Anual',last:'18/11/2025',next:'01/11/2026',owner:'Administración / Responsable centro',status:'done',action:'REALIZADO'},
  {activity:'Estanterías trastienda (archivo/oficina) - inspección visual',category:'Almacén',frequency:'Semestral',last:'17/08/2026',next:'17/02/2027',owner:'Responsable centro',status:'done',action:'REALIZADO'},
  {activity:'Botiquín',category:'Almacén',frequency:'Semestral',last:'17/08/2026',next:'17/02/2027',owner:'Responsable centro',status:'done',action:'REALIZADO'},
  {activity:'Formación Emergency Preparedness-Annual (LearnEx 50009058)',category:'Formación',frequency:'Anual (MAUs)',last:'09/03/2026',next:'09/03/2027',owner:'Todo el personal',status:'done',action:'REALIZADO'},
  {activity:'Plan de Circulación (límite 8 km/h) - revisión',category:'Procedimientos',frequency:'Periódico [propuesta: anual]',last:'30/05/2026',next:'30/05/2027',owner:'Responsable centro',status:'done',action:'REALIZADO'},
  {activity:'Formación Primeros Auxilios (50689913)',category:'Formación',frequency:'Cada 3 años (MAUs)',last:'24/04/2025',next:'24/04/2028',owner:'Equipo de emergencia',status:'done',action:'REALIZADO'},
  {activity:'Formación uso de extintores (hands on) (50954288)',category:'Formación',frequency:'Cada 3 años (MAUs)',last:'06/05/2025',next:'06/05/2028',owner:'Equipo de emergencia',status:'done',action:'REALIZADO'},
  {activity:'MAUs - Plan de Autoprotección revisión/actualización',category:'Emergencias / MAUs',frequency:'3 años',last:'jun-25',next:'01/06/2028',owner:'EHS',status:'done',action:'REALIZADO'},
  {activity:'PRL / Evaluación de Riesgos',category:'PRL / Evaluación de Riesgos',frequency:'Revisión cuando haya cambios',last:'03/02/2025',next:'03/02/2030',owner:'EHS / SC',status:'done',action:'Hablar con Federico'},
  {activity:'Inspección Portón RD 1215 OCA',category:'Portón abatible',frequency:'5 años',last:'25/02/2025',next:'25/02/2030',owner:'Responsable centro',status:'done',action:'REALIZADO'},
  {activity:'Inspección APQ (Almacenamiento de Productos Químicos)',category:'Legal / Licencias',frequency:'5 años',last:'30/01/2026',next:'30/01/2031',owner:'Responsable centro',status:'done',action:'REALIZADO'},
  {activity:'Certificado de Instalación Eléctrica de Baja Tensión (CIE)',category:'Legal / Licencias',frequency:'',last:'09/06/2008',next:'',owner:'SC / EHS',status:'done',action:'REALIZADO, pedido cambio de titularidad'},
  {activity:'Formación CVA en carretillas elevadoras/traspaletas',category:'Formación',frequency:'Según CVA',last:'',next:'',owner:'SC / CVA',status:'open',action:'Reclamado a Antonio Royo'},
  {activity:'Formación CVA en manipulación de botellas',category:'Formación',frequency:'Según CVA',last:'',next:'',owner:'SC / CVA',status:'open',action:'Reclamado a Antonio Royo'},
  {activity:'Formación Mylearning',category:'Formación',frequency:'No periódica',last:'',next:'',owner:'SC / EHS',status:'done',action:'REALIZADO'},
  {activity:'CAE - divulgación MAUs a contratas y visitas',category:'Legal / Licencias',frequency:'',last:'',next:'',owner:'Administración',status:'open',action:'Pendiente vídeo de inducción, enviado email a Federico'},
  {activity:'Tasa de recogida de residuos/basura',category:'Medio Ambiente',frequency:'Anual',last:'',next:'',owner:'',status:'done',action:'Insistir al Ayto de Fuenlabrada para pagarlo'},
  {activity:'Vertidos (autorización y control analítico si aplica)',category:'Medio Ambiente',frequency:'Ver si aplica',last:'',next:'',owner:'SC / EHS (Carla Macedo)',status:'open',action:'Enviado email a Carla Macedo'},
  {activity:'Actualización PR´s extendidos en centro según marco legal',category:'Otros',frequency:'',last:'',next:'',owner:'SC',status:'open',action:'Se observan productos alimentarios extendidos'},
  {activity:'CAE (SC alta en e-coordina)',category:'Otros',frequency:'',last:'',next:'',owner:'SC',status:'done',action:'REALIZADO'},
  {activity:'CRA Alarmas / Intrusión',category:'Otros',frequency:'',last:'',next:'',owner:'SC / EHS',status:'process',action:'Insistido a Javier Santos / James Wolf sobre hombre solo'},
  {activity:'Gestión y entrega de EPI´s establecida',category:'Otros',frequency:'',last:'',next:'',owner:'SC (Pavla Guznarova)',status:'done',action:'Pedir acceso a Share y proveedores, tener un registro'},
  {activity:'Hazardous Enclosures',category:'Otros',frequency:'No aplica',last:'',next:'',owner:'SC / Ingeniería',status:'process',action:'Antonio Espejo está trabajando en ello'},
  {activity:'Plan EHS',category:'Otros',frequency:'',last:'',next:'',owner:'SC / EHS',status:'open',action:'PENDIENTE PLANIFICACIÓN'},
  {activity:'Revisiones de puertas, estanterías, botiquines, EPI´s y lavaojos',category:'Otros',frequency:'',last:'',next:'',owner:'SC / EHS',status:'done',action:'REALIZADO'},
  {activity:'SVA Estudio de Seguridad e Intrusión',category:'Otros',frequency:'',last:'',next:'',owner:'SC / EHS (James Wolf)',status:'process',action:'Insistido por email a James Wolf'},
  {activity:'Trabajos en solitario',category:'Otros',frequency:'',last:'',next:'',owner:'SC / EHS / Ingeniería',status:'process',action:'Insistido a Javier Santos / James Wolf'},
  {activity:'Calendario Laboral',category:'Procedimientos',frequency:'',last:'',next:'',owner:'',status:'done',action:'REALIZADO'},
  {activity:'Instrucciones de Trabajo (IT) - nuevos procedimientos',category:'Procedimientos',frequency:'',last:'',next:'',owner:'SC / EHS',status:'open',action:'PENDIENTE PLANIFICACIÓN'},
  {activity:'Organigrama del centro',category:'Procedimientos',frequency:'',last:'',next:'',owner:'SC / EHS',status:'process',action:'EN PROCESO EHS'},
  {activity:'Programa Comunicación de Riesgos (productos químicos)',category:'Procedimientos',frequency:'',last:'',next:'',owner:'SC / EHS',status:'open',action:'PENDIENTE PLANIFICACIÓN'},
  {activity:'Programa de Conservación Auditiva',category:'Procedimientos',frequency:'',last:'',next:'',owner:'SC / EHS',status:'process',action:'EN PROCESO EHS'},
  {activity:'Programa de Protección Respiratoria',category:'Procedimientos',frequency:'',last:'',next:'',owner:'SC / EHS',status:'process',action:'EN PROCESO EHS'},
  {activity:'Llamar a Serrano e Hijos para confirmar plataformas nuevas',category:'Línea provisional',frequency:'',last:'',next:'07/09/2026',owner:'Responsable centro',status:'open',action:'Confirmar fecha de instalación'},
];
const pendingRows = [
  {person:'Miguel',status:'PENDIENTE',text:'Hablar con Eva de Mérida para revisar qué documentación tienen y organizarnos para completar todo lo pendiente.',priority:'NORMAL',date:'07/09/2026',updated:'31/08/2026'},
  {person:'Miguel',status:'PENDIENTE',text:'Hablar con Properval para revisar las cosas que están pendientes.',priority:'NORMAL',date:'',updated:'31/08/2026'},
  {person:'Miguel',status:'PENDIENTE',text:'Vigilar el uso de los detectores.',priority:'NORMAL',date:'',updated:'31/08/2026'},
  {person:'Miguel',status:'PENDIENTE',text:'Averiguar la fecha de instalación de los detectores permanentes.',priority:'NORMAL',date:'',updated:'31/08/2026'},
  {person:'Miguel',status:'PENDIENTE',text:'Avisar a Federico sobre los EMOC.',priority:'NORMAL',date:'',updated:'31/08/2026'},
  {person:'Miguel',status:'PENDIENTE',text:'Hacer el documento CARAT.',priority:'NORMAL',date:'',updated:'31/08/2026'},
  {person:'Miguel',status:'PENDIENTE',text:'Mirar si algún pintor puede pintar el plan de circulación.',priority:'NORMAL',date:'',updated:'01/09/2026'},
  {person:'Properval',status:'PENDIENTE',text:'Revisar los lavaojos de emergencia.',priority:'NORMAL',date:'',updated:'01/09/2026'},
  {person:'Properval',status:'PENDIENTE',text:'Revisar el desagüe de la máquina exterior de aire acondicionado.',priority:'NORMAL',date:'',updated:'01/09/2026'},
  {person:'Properval',status:'PENDIENTE',text:'Revisar goteras.',priority:'NORMAL',date:'',updated:'01/09/2026'},
  {person:'Properval',status:'PENDIENTE',text:'Cambiar el pomo de la puerta del pasillo.',priority:'NORMAL',date:'',updated:'01/09/2026'},
  {person:'Properval',status:'PENDIENTE',text:'Poner Wi‑Fi al aire acondicionado.',priority:'NORMAL',date:'',updated:'01/09/2026'},
];

const $ = id => document.getElementById(id);
function loadSavedData(){try{const saved=JSON.parse(localStorage.getItem('kurro-data-v1')||'null');if(saved?.center) saved.center.forEach((x,i)=>{if(centerRows[i])Object.assign(centerRows[i],x)});if(saved?.pending) saved.pending.forEach((x,i)=>{if(pendingRows[i])Object.assign(pendingRows[i],x)})}catch(e){}}
function saveData(){try{localStorage.setItem('kurro-data-v1',JSON.stringify({center:centerRows,pending:pendingRows}))}catch(e){}}
function metric(label,value,note,alert=false){return `<div class="metric ${alert?'alert':''}"><div class="metric-label">${label}</div><div class="metric-value">${value}</div><div class="metric-note">${note}</div></div>`}
function statusTag(s){const label=s==='done'?'REALIZADO':s==='process'?'EN PROCESO':'PENDIENTE';return `<span class="status ${s==='done'?'done':s==='process'?'process':'open'}"><span class="status-dot"></span>${label}</span>`}
function addMonths(date, months){const d=new Date(date+'T12:00:00');const day=d.getDate();d.setMonth(d.getMonth()+months);if(d.getDate()!==day)d.setDate(0);return d}
function nextDate(date,frequency){const d=new Date(date+'T12:00:00');const f=(frequency||'').toLowerCase();if(f.includes('seman'))d.setDate(d.getDate()+7);else if(f.includes('bimes'))return addMonths(date,2);else if(f.includes('trimes'))return addMonths(date,3);else if(f.includes('semes'))return addMonths(date,6);else if(f.includes('mens'))return addMonths(date,1);else if(f.includes('5 años'))return addMonths(date,60);else if(f.includes('3 años'))return addMonths(date,36);else if(f.includes('año')||f.includes('anual'))return addMonths(date,12);else return null;return d}
function formatDate(d){return d?`${String(d.getDate()).padStart(2,'0')}/${String(d.getMonth()+1).padStart(2,'0')}/${d.getFullYear()}`:''}
function isOverdue(r){if(!r.next)return false;const p=r.next.split('/');const due=new Date(`${p[2]}-${p[1]}-${p[0]}T23:59:59`);return due<new Date()}
function effectiveStatus(r){return isOverdue(r)&&r.status==='done'?'open':r.status}
function markCenterDone(index){const input=$(`done-date-${index}`);if(!input||!input.value){$('toast').textContent='Elige primero la fecha en la que se ha hecho';$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2800);return}const r=centerRows[index];if(isOverdue(r)){r.status='process';$('toast').textContent='Esta actividad está vencida y no puede marcarse como realizada. Déjala pendiente o en proceso.';$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),3600);renderCenter();return}r.last=formatDate(new Date(input.value+'T12:00:00'));const next=nextDate(input.value,r.frequency);r.next=formatDate(next);r.status='done';r.action='REALIZADO';renderCenter();$('toast').textContent=next?`Marcado como hecho. Próxima revisión: ${r.next}`:'Marcado como hecho. Esta actividad no tiene periodicidad calculable.';$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),3200)}
function updateCenterField(index,field,value){const r=centerRows[index];if(field==='status'&&value==='done'&&isOverdue(r)){r.status='process';$('toast').textContent='Una actividad vencida solo puede estar pendiente o en proceso';$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),3000);renderCenter();return}r[field]=value;saveData();}
function sortValue(r,key){if(key==='category')return r.category;if(key==='last')return r.last?new Date(r.last.split('/').reverse().join('-')):new Date(0);if(key==='next')return r.next?new Date(r.next.split('/').reverse().join('-')):new Date(8640000000000000);if(key==='frequency')return r.frequency||'zzzz';if(key==='status')return r.status;return r.activity}
function renderCenter(){const q=($('center-search').value||'').toLowerCase(), cat=$('center-category').value, state=$('center-status').value, sort=$('center-sort').value;const rows=centerRows.filter(r=>(cat==='all'||r.category===cat)&&(state==='all'||(state==='done'?effectiveStatus(r)==='done':state==='process'?effectiveStatus(r)==='process':effectiveStatus(r)==='open'))&&[r.activity,r.category,r.frequency,r.last,r.next,r.owner,r.action].join(' ').toLowerCase().includes(q)).sort((a,b)=>{const av=sortValue(a,sort),bv=sortValue(b,sort);return av>bv?1:av<bv?-1:0});$('center-table').innerHTML=rows.length?rows.map(r=>{const i=centerRows.indexOf(r),st=effectiveStatus(r),overdue=isOverdue(r);return `<tr><td>${r.activity}</td><td>${r.category}</td><td>${r.frequency||'<span class="muted">Sin periodicidad</span>'}</td><td class="date">${r.last||'<span class="muted">Sin fecha</span>'}</td><td class="date">${r.next||'<span class="muted">Sin fecha</span>'}${overdue?' <span class="overdue-label">VENCIDA</span>':''}</td><td><input class="owner-input" aria-label="Responsable de ${r.activity}" value="${r.owner||''}" placeholder="Sin asignar" onchange="updateCenterField(${i},'owner',this.value)"></td><td><select class="status-select" aria-label="Estado de ${r.activity}" onchange="updateCenterField(${i},'status',this.value)"><option value="open" ${st==='open'?'selected':''}>Pendiente</option><option value="process" ${st==='process'?'selected':''}>En proceso</option>${!overdue?`<option value="done" ${st==='done'?'selected':''}>Realizado</option>`:''}</select></td><td><textarea class="comment-input" rows="2" placeholder="Siguiente acción o comentario" onchange="updateCenterField(${i},'action',this.value)">${r.action||''}</textarea></td><td><div class="row-actions"><input id="done-date-${i}" type="date" aria-label="Fecha realizada para ${r.activity}" ${overdue?'disabled':''}/><button class="done-btn" onclick="markCenterDone(${i})" ${overdue?'disabled':''}>Hecho</button></div></td></tr>`}).join(''):`<tr><td colspan="9" class="empty">No hay resultados con estos filtros.</td></tr>`;$('center-count').textContent=`${rows.length} registros`;}
function renderPending(){const q=($('pending-search').value||'').toLowerCase(), person=window.person||'all', priority=$('pending-priority').value,state=$('pending-status').value;const rows=pendingRows.filter(r=>(person==='all'||r.person===person)&&(priority==='all'||r.priority===priority)&&(state==='all'||r.status===state)&&[r.person,r.text,r.priority].join(' ').toLowerCase().includes(q));$('pending-table').innerHTML=rows.length?rows.map(r=>`<tr><td>${r.status==='PENDIENTE'?'<span class="status open"><span class="status-dot"></span>PENDIENTE</span>':'<span class="status done">REALIZADO</span>'}</td><td>${r.text}</td><td><strong>${r.person}</strong></td><td><span class="priority">${r.priority}</span></td><td class="date">${r.date||'<span class="muted">Sin fecha</span>'}</td><td class="date">${r.updated}</td></tr>`).join(''):`<tr><td colspan="6" class="empty">No hay resultados con estos filtros.</td></tr>`;$('pending-heading').textContent=person==='all'?'Todos mis pendientes':`Pendientes con ${person}`;$('pending-count').textContent=`${rows.length} registros`;}
function init(){const cats=[...new Set(centerRows.map(r=>r.category))].sort();$('center-category').innerHTML='<option value="all">Todas las categorías</option>'+cats.map(c=>`<option>${c}</option>`).join('');$('center-metrics').innerHTML=metric('Actividades registradas',centerRows.length,'Registro maestro')+metric('Pendientes de centro',centerRows.filter(r=>r.status==='open').length,'Requieren seguimiento',true)+metric('En proceso',centerRows.filter(r=>r.status==='process').length,'Acciones abiertas')+metric('Próximas revisiones',centerRows.filter(r=>r.next).length,'Con fecha definida');$('pending-metrics').innerHTML=metric('Pendientes totales',pendingRows.length,'Miguel + Properval')+metric('Con Miguel',pendingRows.filter(r=>r.person==='Miguel').length,'Seguimiento activo')+metric('Con Properval',pendingRows.filter(r=>r.person==='Properval').length,'Seguimiento activo')+metric('Con fecha objetivo',pendingRows.filter(r=>r.date).length,'Para priorizar');$('people-tabs').innerHTML=['all','Miguel','Properval'].map(p=>`<button class="person-tab ${p==='all'?'active':''}" data-person="${p}">${p==='all'?'Todos':p}</button>`).join('');document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));$(`${b.dataset.view}-view`).classList.add('active-view');$('page-title').textContent=b.dataset.view==='center'?'Centro':'Mis pendientes'}));document.querySelectorAll('.person-tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.person-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');window.person=b.dataset.person;renderPending()}));['center-search','center-category','center-status','center-sort'].forEach(id=>$(id).addEventListener('input',renderCenter));['pending-search','pending-priority','pending-status'].forEach(id=>$(id).addEventListener('input',renderPending));document.querySelectorAll('[data-toast]').forEach(b=>b.addEventListener('click',()=>{ $('toast').textContent=b.dataset.toast;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2800)}));renderCenter();renderPending();}window.person='all';init();
function updatePendingField(index,field,value){pendingRows[index][field]=value;saveData()}
function markPendingDone(index){pendingRows[index].status='REALIZADO';pendingRows[index].updated=formatDate(new Date());saveData();renderPending()}
setTimeout(()=>renderPending(),0);
setTimeout(()=>{loadSavedData();renderCenter();renderPending()},0);
renderPending=function(){const q=($('pending-search').value||'').toLowerCase(),person=window.person||'all',priority=$('pending-priority').value,state=$('pending-status').value;const rows=pendingRows.filter(r=>(person==='all'||r.person===person)&&(priority==='all'||r.priority===priority)&&(state==='all'||r.status===state)&&[r.person,r.text,r.priority,r.comments].join(' ').toLowerCase().includes(q));$('pending-table').innerHTML=rows.length?rows.map(r=>{const i=pendingRows.indexOf(r);return `<tr><td><select class="status-select" onchange="updatePendingField(${i},'status',this.value)"><option ${r.status==='PENDIENTE'?'selected':''}>PENDIENTE</option><option ${r.status==='REALIZADO'?'selected':''}>REALIZADO</option></select></td><td>${r.text}</td><td><strong>${r.person}</strong></td><td><select class="status-select" onchange="updatePendingField(${i},'priority',this.value)"><option ${r.priority==='NORMAL'?'selected':''}>NORMAL</option><option ${r.priority==='ALTA'?'selected':''}>ALTA</option></select></td><td class="date">${r.date||'<span class="muted">Sin fecha</span>'}</td><td class="date">${r.updated}</td><td><textarea class="comment-input" rows="2" placeholder="Añadir comentario" onchange="updatePendingField(${i},'comments',this.value)">${r.comments||''}</textarea></td><td><button class="done-btn" onclick="markPendingDone(${i})" ${r.status==='REALIZADO'?'disabled':''}>Hecho</button></td></tr>`}).join(''):`<tr><td colspan="8" class="empty">No hay resultados con estos filtros.</td></tr>`;$('pending-heading').textContent=person==='all'?'Todos mis pendientes':`Pendientes con ${person}`;$('pending-count').textContent=`${rows.length} registros`};
// Sincronización con Google Sheets para la versión web pública.
const KURRO_API='https://script.google.com/macros/s/AKfycbwBWLM0kD6MB6n35yM33J1whw12JRCEODsFvEtWXxifmrGeqesVDDMsBrewOkExY5iM7A/exec';
function kurroRequest(params){return new Promise((resolve,reject)=>{const cb='kurro_'+Date.now()+'_'+Math.random().toString(36).slice(2);const script=document.createElement('script');const timer=setTimeout(()=>{delete window[cb];script.remove();reject(new Error('Tiempo de espera agotado'))},12000);window[cb]=data=>{clearTimeout(timer);delete window[cb];script.remove();data&&data.ok?resolve(data.result):reject(new Error('Respuesta no válida'))};script.onerror=()=>{clearTimeout(timer);delete window[cb];script.remove();reject(new Error('No se pudo conectar'))};params.callback=cb;script.src=KURRO_API+'?'+new URLSearchParams(params).toString();document.body.appendChild(script)})}
function remotePlanningRow(row,index){const y=row[11]||'';let status=/REALIZADO|ACEPTADO/i.test(y)?'done':'open';return{activity:row[0]||'',category:row[1]||'Otros',frequency:row[2]||'',last:row[3]||'',next:row[4]||'',owner:row[5]||'',status,action:row[9]||'',serverRow:index+2}}
function remotePendingRow(row,index,person,fileId){return{person,status:String(row[0]||'PENDIENTE').toUpperCase(),comments:row[1]||'',text:row[2]||'',priority:String(row[3]||'NORMAL').toUpperCase(),date:row[4]||'',updated:row[5]||'',closed:row[6]||'',serverRow:index+2,fileId}}
async function loadRemoteData(){try{const data=await kurroRequest({api:'data'});if(data.planning?.values?.length){centerRows.splice(0,centerRows.length,...data.planning.values.slice(1).filter(r=>r.some(Boolean)).map(remotePlanningRow));centerRows.forEach((r,i)=>r.serverRow=i+2)}const p=[];for(const source of [{data:data.miguel,person:'Miguel'},{data:data.properval,person:'Properval'}])if(source.data?.values?.length)source.data.values.slice(1).filter(r=>r.some(Boolean)).forEach((r,i)=>p.push(remotePendingRow(r,i,source.person,source.data.id)));pendingRows.splice(0,pendingRows.length,...p);refreshKURROMetrics();renderCenter();renderPending()}catch(e){console.warn('No se pudo actualizar la vista',e)}}
let kurroPendingWrites=0;
let kurroRefreshInFlight=false;
function remoteWrite(request){kurroPendingWrites++;return request.finally(()=>{kurroPendingWrites--})}
function isEditingKURRO(){const active=document.activeElement;return active&&(['INPUT','TEXTAREA','SELECT'].includes(active.tagName)||active.isContentEditable)}
function showSyncToast(message){const toast=$('toast');if(!toast)return;toast.textContent=message;toast.classList.add('show');clearTimeout(window.kurroToastTimer);window.kurroToastTimer=setTimeout(()=>toast.classList.remove('show'),2200)}
function refreshKURROMetrics(){if($('center-metrics'))$('center-metrics').innerHTML=metric('Actividades registradas',centerRows.length,'Registro maestro')+metric('Pendientes de centro',centerRows.filter(r=>effectiveStatus(r)==='open').length,'Requieren seguimiento',true)+metric('En proceso',centerRows.filter(r=>effectiveStatus(r)==='process').length,'Acciones abiertas')+metric('Próximas revisiones',centerRows.filter(r=>r.next).length,'Con fecha definida');if($('pending-metrics'))$('pending-metrics').innerHTML=metric('Pendientes totales',pendingRows.filter(r=>r.status!=='REALIZADO').length,'Miguel + Properval')+metric('Con Miguel',pendingRows.filter(r=>r.person==='Miguel'&&r.status!=='REALIZADO').length,'Seguimiento activo')+metric('Con Properval',pendingRows.filter(r=>r.person==='Properval'&&r.status!=='REALIZADO').length,'Seguimiento activo')+metric('Con fecha objetivo',pendingRows.filter(r=>r.date&&r.status!=='REALIZADO').length,'Para priorizar')}
async function refreshKURROFromSheets(silent=false){if(kurroRefreshInFlight||kurroPendingWrites||isEditingKURRO())return;kurroRefreshInFlight=true;try{await loadRemoteData();if(!silent)showSyncToast('Datos actualizados desde Google Sheets')}finally{kurroRefreshInFlight=false}}
setInterval(()=>{if(document.visibilityState==='visible')refreshKURROFromSheets(true)},30000);
window.addEventListener('focus',()=>refreshKURROFromSheets(true));
document.querySelector('[data-refresh]')?.addEventListener('click',async()=>{const button=document.querySelector('[data-refresh]');button?.classList.add('busy');if($('sync-label'))$('sync-label').textContent='Actualizando…';await refreshKURROFromSheets(false);if($('sync-label'))$('sync-label').textContent='Sincronizado';button?.classList.remove('busy')});
const localUpdateCenterField=updateCenterField;updateCenterField=function(index,field,value){const r=centerRows[index];if(field==='status'&&value==='done'&&isOverdue(r)){r.status='process';renderCenter();return}r[field]=value;saveData();if(r.serverRow){const col=field==='owner'?7:field==='action'?10:field==='status'?12:null;if(col)remoteWrite(kurroRequest({api:'updateCell',fileId:'1AiIsFZCyZVp4ERTi0ExreV10StjayEw9tLWv4W21foQ',sheetName:'Registro Maestro',row:r.serverRow,column:col,value:field==='status'?(value==='done'?'REALIZADO':value==='process'?'EN PROCESO':'PENDIENTE'):value}).catch(()=>{}))}renderCenter()};
const localMarkCenterDone=markCenterDone;markCenterDone=function(index){const r=centerRows[index],input=$(`done-date-${index}`);if(!input?.value||isOverdue(r)){localMarkCenterDone(index);return}if(r.serverRow)remoteWrite(kurroRequest({api:'markPlanningDone',row:r.serverRow,dateText:input.value})).then(()=>loadRemoteData()).catch(()=>localMarkCenterDone(index));else localMarkCenterDone(index)};
const localUpdatePendingField=updatePendingField;updatePendingField=function(index,field,value){const r=pendingRows[index];r[field]=value;saveData();if(r.fileId&&r.serverRow){remoteWrite(kurroRequest({api:'updatePending',fileId:r.fileId,row:r.serverRow,field,value}).catch(()=>{}))}renderPending()};
const localMarkPendingDone=markPendingDone;markPendingDone=function(index){const r=pendingRows[index];r.status='REALIZADO';if(r.fileId&&r.serverRow)remoteWrite(kurroRequest({api:'updatePending',fileId:r.fileId,row:r.serverRow,field:'status',value:'REALIZADO'})).then(()=>loadRemoteData()).catch(()=>localMarkPendingDone(index));else localMarkPendingDone(index)};
loadRemoteData();
function updatePendingField(index,field,value){pendingRows[index][field]=value;saveData()}
function markPendingDone(index){pendingRows[index].status='REALIZADO';pendingRows[index].updated=formatDate(new Date());saveData();renderPending()}
renderPending=function(){const q=($('pending-search').value||'').toLowerCase(),person=window.person||'all',priority=$('pending-priority').value,state=$('pending-status').value;const rows=pendingRows.filter(r=>(person==='all'||r.person===person)&&(priority==='all'||r.priority===priority)&&(state==='all'||r.status===state)&&[r.person,r.text,r.priority,r.comments].join(' ').toLowerCase().includes(q));$('pending-table').innerHTML=rows.length?rows.map(r=>{const i=pendingRows.indexOf(r);return `<tr><td><select class="status-select" onchange="updatePendingField(${i},'status',this.value)"><option ${r.status==='PENDIENTE'?'selected':''}>PENDIENTE</option><option ${r.status==='REALIZADO'?'selected':''}>REALIZADO</option></select></td><td>${r.text}</td><td><strong>${r.person}</strong></td><td><select class="status-select" onchange="updatePendingField(${i},'priority',this.value)"><option ${r.priority==='NORMAL'?'selected':''}>NORMAL</option><option ${r.priority==='ALTA'?'selected':''}>ALTA</option></select></td><td class="date">${r.date||'<span class="muted">Sin fecha</span>'}</td><td class="date">${r.updated}</td><td><textarea class="comment-input" rows="2" placeholder="Añadir comentario" onchange="updatePendingField(${i},'comments',this.value)">${r.comments||''}</textarea></td><td><button class="done-btn" onclick="markPendingDone(${i})" ${r.status==='REALIZADO'?'disabled':''}>Hecho</button></td></tr>`}).join(''):`<tr><td colspan="8" class="empty">No hay resultados con estos filtros.</td></tr>`;$('pending-heading').textContent=person==='all'?'Todos mis pendientes':`Pendientes con ${person}`;$('pending-count').textContent=`${rows.length} registros`};
